### ISSUE TITLE
App crashes after submit button pressed.

### ISSUE THREAD

**Issue by gkaldev** [firebase/friendlypix-android#9]
_From @shubham-git on February 9, 2017 23:25_

java.lang.RuntimeException: An error occurred while executing doInBackground()

at com.google.android.gms.common.internal.zzab.zzb(Unknown Source)
 at com.google.firebase.storage.StorageReference.child(Unknown Source)

on
 final StorageReference fullSizeRef = photoRef.child(FirebaseUtil.getCurrentUserId()).child("full").child(timestamp.toString()).child(fileName + ".jpg");
            final StorageReference thumbnailRef = photoRef.child(FirebaseUtil.getCurrentUserId()).child("thumb").child(timestamp.toString()).child(fileName + ".jpg");

_Copied from original issue: firebase/friendlypix#80_

**Comment by gkaldev** [comment]
_From @yofu1234 on February 17, 2017 5:39_

Check this PR: https://github.com/firebase/friendlypix/pull/57 for the fix.

**Comment by gkaldev** [comment]
_From @nicolasgarnier on April 2, 2017 8:5_

@gkaldevrel Could you have a look at this? There seem to be a PR that fixes the issue (thx @yofu1234).

**Comment by gkaldev** [comment]
Cleaning up issue fixed in upcoming v2.
